<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ListagemDePessoas.aspx.cs" Inherits="AgendaDeContatos.ListagemDePessoas" %>

<asp:Content ContentPlaceHolderID="MainContent" runat="server">
    <div class="container">
        <br />
        <div class="panel panel-default">
            <div class="panel-heading">
                Listagem de Pessoas
            </div>
            <div class="panel-body">
                <fieldset class="col-md-7">
                    <legend>Contatos Cadastrados</legend>
                    <div class="form-row">
                        <div class="form-group col-lg-6">
                            <p>Nome:</p>
                            <asp:TextBox ID="txtNome" CssClass="form-control" runat="server"></asp:TextBox>
                        </div>
                        <div class="form-group col-lg-6">
                            <p>Cpf:</p>
                            <asp:TextBox ID="txtCpf" CssClass="form-control" runat="server"></asp:TextBox>
                        </div>
                    </div>
                </fieldset>
                <asp:Button ID="btnListar" Style="margin-right: 50px; margin-top: 80px;" CssClass="btn btn-primary mb-2" runat="server" Text="Pesquisar" OnClick="btnListar_Click" />
                <asp:Button ID="btnCriar" Style="margin-top: 80px;" runat="server" CssClass="btn btn-success mb-2" Text="Cadastrar" OnClick="btnCriar_Click" />

            </div>
        </div>
    </div>
    <div class="container table-responsive">
        <asp:GridView ID="GridView1" CssClass="table table-striped table-hover"
            Width="100%" runat="server" AutoGenerateEditButton="True"
            AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting">
        </asp:GridView>
        <asp:Button ID="btnLimpar" Style="margin-right: 50px; margin-top: 80px;" CssClass="btn btn-primary mb-2" runat="server" Text="Limpar Lista" OnClick="btnLimpar_Click" />

    </div>
</asp:Content>
