<%@ Page Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ListagemDePessoas.aspx.cs" Inherits="AgendaDeContatos.ListagemDePessoas" %>

<asp:Content ContentPlaceHolderID="MainContent" runat="server">
    <div class="container">
        <br />
        <div class="panel panel-default">
            <div class="panel-heading">
                Listagem de Pessoas
            </div>
            <div class="panel-body">
                <fieldset class="col-md-7">
                    <legend>Contatos Cadastrados</legend>
                    <div class="form-inline">
                        <div class="form-group mb-2">
                            <p>Nome:</p>
                            <asp:TextBox ID="txtNome" CssClass="form-control" runat="server"></asp:TextBox>
                        </div>
                        <div class="form-group mx-sm-3 mb-2">
                            <p>Cpf:</p>
                            <asp:TextBox ID="txtCpf" CssClass="form-control Cpf" runat="server"></asp:TextBox>
                        </div>
                        <div style="float: right">
                            <asp:Button ID="Button1" Style="margin-right: 50px; margin-top: 30px;" CssClass="btn btn-primary mb-2" runat="server" Text="Pesquisar" />
                            <asp:Button ID="Button2" Style="margin-top: 30px;" runat="server" CssClass="btn btn-success mb-2" Text="Cadastrar" />
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
    </div>
    <div class="container table-responsive">
        <asp:GridView ID="GridView1" CssClass="table table-striped table-hover" 
            Width="100%" runat="server" AutoGenerateEditButton="True" 
            AutoGenerateDeleteButton="True"></asp:GridView>
    </div>
</asp:Content>
